apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-sonarqube
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ibmc-vpc-block-10iops-tier
  resources:
    requests:
      storage: 10Gi
